name: 'PHPCS Drupal check with Annotations'
description: 'PHPCS Drupal checker with auto annotations out of the box'
author: 'Timo Bubigo'
inputs:
  memory_limit:
    description: 'Define the memory limit to use. Default: 256M.'
    required: false
    default: '256M'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'code'
  color: 'blue'
